web/modules/imaging/includes/logs.inc.php
web/modules/imaging/includes/xmlrpc.inc.php
web/modules/imaging/manage/ajaxLogs.php
web/modules/imaging/manage/location.php
web/modules/imaging/manage/master_add.php
web/modules/imaging/manage/postinstall_edit.php
web/modules/pkgs/graph/js/class.js
web/modules/pkgs/pkgs/appstreamSettings.php

Thanks for fixing these typos.

Fix minor typos

---

web/modules/backuppc/backuppc/hostSummary.php
web/modules/dyngroup/includes/groups.inc.php
web/modules/imaging/includes/includes.php
web/modules/inventory/inventory/addEntityRule.php
web/modules/msc/includes/widgets.inc.php
web/modules/msc/msc/vnc_client_java.php

Sorry for not noticing these typos earlier.

Fix another bunch of minor typos

---

services/mmc/plugins/xmppmaster/config.py

Addition parameter for agent base on Master.

auto update agent 1

---

services/mmc/plugins/glpi/__init__.py
services/mmc/plugins/glpi/database_91.py
web/modules/glpi/glpi/createMachinesStaticGroup.php
web/modules/glpi/includes/xmlrpc.php

When the group is composed by a big amount of machines, the group takes several seconds to create it. This commit improve the speed even if it is not perfect.

(dashboard) Improve the creation of the groups for machineOnline widget.

---

web/modules/dyngroup/dyngroup/add_groups.php

permet l'edition des group d'imaging static.

imaging. edition machine after creation

---

services/mmc/plugins/dyngroup/__init__.py
services/mmc/plugins/dyngroup/database.py
services/pulse2/database/dyngroup/__init__.py
web/modules/dyngroup/includes/dyngroup.php
web/modules/glpi/glpi/createBackupStaticGroup.php
web/modules/glpi/glpi/createMachinesStaticGroup.php

This modification includes a new xmlrpc function to add a computer list to the specified group.

(dashboard) improve the creation group speed for widgets

---

services/mmc/plugins/xmppmaster/config.py
services/mmc/plugins/xmppmaster/master/agentmaster.py

- new registration of the machine if 1 incoherence in the xmppmaster database appears between the machine table and the network table.

[fixe] - Coherency control between glpi and xmpp

---

services/mmc/plugins/dyngroup/database.py
services/mmc/plugins/imaging/functions.py
services/mmc/plugins/msc/__init__.py
services/pulse2/database/msc/__init__.py
services/pulse2/database/xmppmaster/__init__.py
web/modules/msc/msc/ajaxPackageFilter.php
web/modules/msc/msc/convergence.php
web/modules/msc/msc/launch.php

Convergence

---

services/mmc/plugins/msc/database.py

The sql session differs if the connexion is a remote connexion or a local connexion.

[BUGFIX] Check if the database connexion is a local or a remote connexion

---

services/mmc/plugins/glpi/database_084.py
services/mmc/plugins/glpi/database_92.py
web/modules/glpi/glpi/ajaxMachinesList.php

(cherry picked from commit 3466f31fd4ca0d4bd492c594365f3643967f352e)

[Computers list] Refactoring the computers list

---

services/pulse2/database/xmppmaster/__init__.py

(cherry picked from commit 7014ba84917958ec548a25ca3d34e4a8683041d4)

[guacamole] Force configuration of guacamole if no connection present

---

services/pulse2/scheduler/analyses.py
services/pulse2/scheduler/phases/remote.py
services/pulse2/scheduler/queries.py
services/pulse2/scheduler/types.py
services/pulse2/time_intervals.py
services/pulse2/utils.py
tests/services/mmcagent-dyngroup-empty.py

This pull request fixes in old pulse code the use of == or != against is and is not.
We need to use is and is not when comparing to None

[QA] Uses is and is not when comparing to None

---

web/modules/msc/includes/package_api.php
web/modules/msc/msc/ajaxPackageFilter.php
web/modules/msc/msc/launch.php
web/modules/pulse2/includes/menu_action.php

Remove php notice in package page.

[Deployment view] Remove some php notice

---

services/mmc/plugins/msc/__init__.py

[QA] Fix codestyle errors

---

services/pulse2/database/xmppmaster/__init__.py

in the array the start element was here twice.
Let's remove the incorrect one.
Rename dd variable to a more understandable name.

[getdeploybyuser] Fix getdeploybyuser function

---

services/mmc/plugins/glpi/database_92.py
services/mmc/plugins/glpi/database_94.py
web/modules/glpi/includes/html.php

fixes pulse-project/siveo-todo#239

Add the column firmware to the filter

---

web/modules/pkgs/graph/js/class.js
web/modules/pkgs/includes/actions/action_download.php

fixes pulse-project/siveo-todo#251
(cherry picked from commit 9c12bd7a5627fdf259a09136cca6e3b603dc478b)

downloadstep

---

services/mmc/plugins/xmppmaster/__init__.py
services/mmc/plugins/xmppmaster/master/pluginsmaster/plugin_reversessh_AM_ARS.py
web/modules/xmppmaster/includes/xmlrpc.php

fixes pulse-project/siveo-todo#243

[reversessh] Create reversessh for remote file browser

---

services/mmc/plugins/glpi/database.py
services/mmc/plugins/glpi/database_100.py

Add support for the new glpi 10.0 version:
-> https://github.com/glpi-project/glpi/releases/tag/10.0.0

(glpi) Add glpi 10.0 support

---

services/mmc/plugins/xmppmaster/master/pluginsmaster/plugin_resultkiosk.py

The syncthing parameter where missing on addlogincommand function

[kiosk] Add missing parameter on install command

---

services/contrib/Makefile.am
services/contrib/xmppmaster/sql/schema-074.sql
services/mmc/plugins/xmppmaster/__init__.py
services/pulse2/database/xmppmaster/__init__.py
services/pulse2/database/xmppmaster/schema.py
web/modules/xmppmaster/includes/xmlrpc.php
web/modules/xmppmaster/xmppmaster/ActionQuickconsole.php
web/modules/xmppmaster/xmppmaster/QAcustommachgrp.php
web/modules/xmppmaster/xmppmaster/ajaxGroupactionquick.php

For this we need to add jid column in command_qa and command_action.

[QA] Use jid in quick action results instead of Id coming from glpi

---

services/contrib/kiosk/sql/schema-006.sql
services/mmc/plugins/kiosk/__init__.py
services/pulse2/database/kiosk/__init__.py
services/pulse2/database/kiosk/schema.py
web/modules/kiosk/kiosk/add.php
web/modules/kiosk/kiosk/ajaxAddProfile.php
web/modules/kiosk/kiosk/ajaxEditProfile.php
web/modules/kiosk/kiosk/editProfile.php

Use pkgs.packages instead of kiosk.package. Now we have QSoftware, QVendor, QVersion and we can check if this is matching

[KIOSK] Improve package detection

---

services/contrib/kiosk/sql/schema-007.sql
services/mmc/plugins/xmppmaster/master/pluginsmaster/plugin_resultkiosk.py
services/pulse2/database/kiosk/__init__.py
services/pulse2/database/kiosk/schema.py

The users asks re saved in database.

[kiosk] save acknowledgements for all asked packages

---

services/mmc/plugins/kiosk/__init__.py
services/pulse2/database/kiosk/__init__.py

If the package tagged "ask" is associated to the profile, we seek acknowledgements

[KIOSK] add acknowledgements to the packages list

---

services/mmc/plugins/kiosk/__init__.py
services/pulse2/database/kiosk/__init__.py
web/modules/kiosk/includes/xmlrpc.php
web/modules/kiosk/infoPackage.inc.php
web/modules/kiosk/kiosk/ajaxProfilesList.php
web/modules/kiosk/kiosk/deleteProfile.php
web/modules/kiosk/kiosk/index.php

Also activate the filter on name

[KIOSK] display profiles list in paginated table

---

web/modules/imaging/imaging/tabs.php

The group id was not sent to the function

[IMAGING] Add missing modification

---

web/modules/base/computers/delete.php

We had an error when deleting a machine, indeed it was indicated that the machine was not deleted, now it is clearly indicated that the machine has been deleted.

(computers) Fix deleting

---

web/includes/PageGenerator.php

We need this in order to adapt our code to playwrights tests

(PageGenerator) function used to add an ID to a <tr id=...> tag

---

web/modules/admin/admin/ajaxRelaysList.php

Adding an id ($relays['datas']['id']) to the tr tag for playwright tests, starting the id with a 'r' to avoid any problems with playwright

(RelayList) Adding cssids to the 'List of relays' tab

---

web/modules/admin/admin/ajaxRelaysList.php

Changing from $datas['id'] to $pramas['jid']

(RelayList) Changing cssid for tests

---

web/modules/dyngroup/dyngroup/ajaxListGroups.php

Adding an id ($ids['0']['groupname']) to the tr tag for playwright tests, starting the id with a 'g' to avoid any problems with playwright

(ListGroup) adding an id to the <tr id=...> tag

---

web/modules/base/users/ajaxFilter.php

Adding a ';' at the end of line 75

(ListUsers) Correction, users list page not working

---

web/modules/updates/updates/ajaxEntitiesList.php

Adding an id ($entityNames) to the tr tag for playwright tests, starting the id with a 'e_' to avoid any problems with playwright

(Updates_Entities_List) adding an id to the <tr id=...> tag

---

web/modules/pkgs/pkgs/ajaxPackageList.php

Changing from 'p' to 'p_' for clarity

(Pkgs_List) changing separator on the <tr id=...> tag

---

web/modules/pkgs/includes/actions/action_unzip_file.php

We add id and class for playwright tests in unzip_file action at different <input> tags

(Create package action) Add ids and class

---

web/modules/pkgs/includes/actions/action_download.php

We add the class url_name in the <input> tag with the attribute name="url" and class action in the <h1> tag for playwright tests

(Create packages actions) Add class

---

web/modules/pkgs/includes/actions/action_command_natif_shell.php
web/modules/pkgs/includes/actions/action_comment.php
web/modules/pkgs/includes/actions/action_kiosknotification.php
web/modules/pkgs/includes/actions/action_loop_question.php
web/modules/pkgs/includes/actions/action_notification.php
web/modules/pkgs/includes/actions/action_pwd_package.php
web/modules/pkgs/includes/actions/action_question.php
web/modules/pkgs/includes/actions/action_section_install.php
web/modules/pkgs/includes/actions/action_section_launch.php
web/modules/pkgs/includes/actions/action_section_uninstall.php
web/modules/pkgs/includes/actions/action_section_update.php
web/modules/pkgs/includes/actions/action_set_config_file.php
web/modules/pkgs/includes/actions/action_set_environ.php
web/modules/pkgs/includes/actions/actioncleaning.php
web/modules/pkgs/includes/actions/actionprocessscript.php
web/modules/pkgs/includes/actions/actionprocessscriptfile.php
web/modules/pkgs/includes/actions/actionrestart.php
web/modules/pkgs/includes/actions/actionwaitandgoto.php

We add the class action in each <h1> tag of each action for playwright tests

(Create package action) Add class

---

web/modules/pkgs/pkgs/edit.php

We fix a file display problem when editing a package. The list of files was no longer displayed after validation of the edition

[Packages] Fix listing files in a package after saving changes in the package

---

web/modules/updates/updates/ajaxUpdatesListWinGray.php

We add to each <tr> tag an id corresponding to its updateid with "u_" in front of each id

(updatesListWin) Add id to <tr> tag

---

web/modules/updates/updates/ajaxUpdatesListWinGray.php

(updatesListWin) Fix id to <tr> tag

---

services/mmc/plugins/xmppmaster/__init__.py
services/pulse2/database/xmppmaster/__init__.py
services/pulse2/database/xmppmaster/schema.py
web/graph/global.css
web/modules/xmppmaster/includes/xmlrpc.php
web/modules/xmppmaster/xmppmaster/logs/viewmachinelogs.php

On update audit deploy, show the info and help actions
(cherry picked from commit d4a859e465e35605ec380777e5bb23fad3ea1c82)

(updates) add info and help link for updates audit

---

services/contrib/Makefile.am
services/contrib/imaging/sql/schema-026.sql
services/mmc/plugins/imaging/functions.py
services/pulse2/database/imaging/__init__.py
services/pulse2/package_server/imaging/api/functions.py
services/pulse2/package_server/imaging/computer.py
services/pulse2/package_server/imaging/menu.py
web/imaging/bootmenu.php
web/modules/imaging/imaging/images.php
web/modules/imaging/imaging/multicast.php
web/modules/imaging/includes/xmlrpc.inc.php
web/modules/imaging/manage/ajaxConfiguration.php
web/modules/imaging/manage/multicastaction.php
web/modules/imaging/manage/save_configuration.php

Previously we used text files to send menus to iPXE ( the same way we did with PXELinux ).
Now, with iPXE we can store all in the SQL Database and retrieve it though SQL Request via a PHP Webpage.
It will remove bugs related to files synchronisation between relays.
If the KEYBOARD_MAP is set to dynamic, the keyboard will be handled. Source : https://ipxe.org/buildcfg/keyboard_map

(FEATURE) Use iPXE new way of using menus.
